services:
  ##########################
  storage-node-0:
    image: storage-server
    build:
      context: ../ ## src/ (i.e. one level up from where docker-compose.yml is located right now)
      dockerfile: storage/Dockerfile
    ports:
      - "8081:8080"  
    environment:
      - PORT=8080  
      - NODE_ID=0
    restart: always
    container_name: Node_0

  storage-node-1:
    image: storage-server
    build:
      context: ../
      dockerfile: storage/Dockerfile 
    ports:
      - "8082:8080" 
    environment:
      - PORT=8080
      - NODE_ID=1
    restart: always
    container_name: Node_1

  storage-node-2:
    image: storage-server
    build:
      context: ../
      dockerfile: storage/Dockerfile
    ports:
      - "8083:8080"  
    environment:
      - PORT=8080
      - NODE_ID=2
    restart: always
    container_name: Node_2

  storage-node-3:
    image: storage-server
    build:
      context: ../
      dockerfile: storage/Dockerfile
    ports:
      - "8084:8080"  
    environment:
      - PORT=8080
      - NODE_ID=3
    restart: always
    container_name: Node_3

  storage-node-4:
    image: storage-server
    build:
      context: ../
      dockerfile: storage/Dockerfile
    ports:
      - "8085:8080"  
    environment:
      - PORT=8080
      - NODE_ID=4
    restart: always
    container_name: Node_4
  ##########################
